---
# Week 3 Ansible Assignment by Jorge Otero
- hosts: webservers
  tasks: 
    - name: upgrade all packages
      become: yes
      yum: name=* state=latest

    - name: install node and npm
      become: yes
      yum:
        enablerepo: epel
        state: installed
        name:
          - nodejs
          - npm

    - name: install mySQL
      become: yes
      yum:
        state: installed
        name:
          - mysql
    
    - name: Copying the application file
      copy:
        src: helloworld.js
        dest: /home/ec2-user/
        owner: ec2-user
        group: ec2-user
        mode: 0644
      notify: restart helloworld

    - name: Copying the upstart file
      become: yes
      copy:
        src: helloworld.conf
        dest: /etc/init/helloworld.conf
        owner: root
        group: root
        mode: 0644

    - name: Starting the HelloWorld node service
      become: yes
      service:
        name: helloworld
        state: started
