Description: 'Modified SWDV660 Template by Jorge Otero'
Outputs:
  InstancePublicIp:
    Description: Public IP of our instance.
    Value: !GetAtt 
      - instance
      - PublicIp
  WebUrl:
    Description: Application endpoint
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - instance
          - PublicDnsName
        - ':'
        - '3333'
Parameters:
  KeyPair:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to SSH
    Type: 'AWS::EC2::KeyPair::KeyName'
Resources:
  SecurityGroup:
    Properties:
      GroupDescription: Allow SSH and TCP/3000 access
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: 0.0.0.0/0
          FromPort: '3000'
          IpProtocol: tcp
          ToPort: '3000'
    Type: 'AWS::EC2::SecurityGroup'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7aed6789-0f1c-4ef8-b640-b3e72a558f58
  instance:
    Properties:
      ImageId: ami-cfe4b2b0
      InstanceType: t2.nano
      KeyName: !Ref KeyPair
      SecurityGroups:
        - !Ref SecurityGroup
      UserData: !Base64 
        'Fn::Join':
          - |+

          - - '#!/bin/bash'
            - sudo yum install --enablerepo=epel -y nodejs
            - mkdir week3_files
            - 'wget https://raw.githubusercontent.com/jorgieo/SWDV-660-1W-20-FA1_OTERO/master/Week%202/helloworld.js -O /home/ec2-user/week3_files/helloworld.js'
            - 'wget http://bit.ly/2vVvT18 -O /etc/init/helloworld.conf'
            - start helloworld
      Tags: 
        - Key: "Name"
          Value: "Week3Nano"
        - Key: "InstanceType"
          Value: "T2.nano"
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ea709219-c1a1-449f-93f6-b19a17f884b9
Metadata:
  'AWS::CloudFormation::Designer':
    7aed6789-0f1c-4ef8-b640-b3e72a558f58:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    ea709219-c1a1-449f-93f6-b19a17f884b9:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 7aed6789-0f1c-4ef8-b640-b3e72a558f58
